language: node_js

node_js:
    - "0.12"

# whitelisted branches
branches:
    only:
        - master
        - development

before_install:
    - npm install -g typescript typings mocha istanbul
    - typings install
    
before_script:
    - npm run build
    
script:
    - npm run test

after_success:
    - npm run coverage
    - npm run report-coverage

