language: node_js

node_js:
    - "0.12"

# whitelisted branches
branches:
    only:
        - master
        - stable
        - beta

before_install:
    - npm install -g grunt-cli
    - npm install -g mocha